app = 'fajar-discord-bot'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]

[http_service]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256