app = 'fajar-discord-bot'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]
    PORT = '8888'

[http_service]
    internal_port = 8888
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256